### ISSUE TITLE
[BUG] 404 Not Found

### ISSUE THREAD

**Issue by xfk97** [openai/gpt-discord-bot#62] opened 2023-04-15 02:00 UTC
I started the bot on a virtual environment using these commands:
python3 -m venv env_name
source env_name/bin/activate
pip install -r /Users/fk/Downloads/gpt-discord-bot-main/requirements.txt 
python3 /Users/fk/Downloads/gpt-discord-bot-main/main.py

Bot starts up, but whenever I try to use /chat I get this:

`discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction`

<img width="286" alt="Screen Shot 2023-04-14 at 9 56 50 PM" src="https://user-images.githubusercontent.com/110437155/232177696-d07b2c6b-34bf-4209-8902-483300aba1e5.png">

MacOS Big Sur 11.7

**Comment by Kav-K** [comment] 2023-12-31 09:24
Hi @xfk97 have you checked that the bot has all the required permissions and that you are able to invoke slash commands in the channel that you're trying to use the bot in?

**Comment by Kav-K** [comment] 2024-01-07 07:57
@xfk97 This was not locally reproducible for me, we'll close this issue out but please feel free to reopen if you are still experiencing this after making sure the bot has all the necessary permissions.

**Comment by CartoonChess** [comment] 2024-01-08 00:42
I’m getting the same issue. The bot was running fine for a few hours, then this issue came up. I couldn’t create new threads, but it would still respond to old ones. I restarted the process but the bug persists, but as it won’t respond to existing threads after restarting, it now won’t respond to anything. Looking at the errors, it appears to trace back to moderation functions, but I’m unsure.

I had previously purposely triggered moderation by threatening the bot. I wonder if this could be related?

Edit: That seems likely to be the case. I used another user account and the bot starts a new thread as expected. When using the first (moderated?) user to respond in the newly created thread, the bot responds with error 500, whereas it continues to respond to the second (unmoderated) user.

Edit 2: This doesn’t appear to be set in stone, because the “moderated” user can still occasionally get the bot to start a thread (in testing, about once in ten, even though they all use a simple “hi” prompt).

Edit 3: Rebuilding the bot also didn’t help, but giving it a new API key appears to have erased its memory, so perhaps this is noted on OpenAI’s side?

**Comment by CalebTechie** [comment] 2024-01-09 13:34
I am also getting this same issue. the bot joins the server just fine but when I use /chat. The bot says the application didn't respond 
I set my bot to have admin permissions which is integer code 8 and hard coded the permissions number in the BOT_INVITE_URL to be the same and I get an error 429 instead 
![image](https://github.com/openai/gpt-discord-bot/assets/109525639/2b6dea18-06a2-4790-9179-c8726584959a)

Using Windows and Python 3.10

**Closed as completed** 2024-01-09 18:51 UTC
Labels: bug
